Update vmw_getcert

diff --git a/vmw_getcert b/vmw_getcert
--- a/vmw_getcert
+++ b/vmw_getcert
@@ -7,21 +7,25 @@ Usage: ${0##*/} [-hv] -c CERT_CN -a CRED_FILE [OPTIONS] FQDN
 This script requests a certificate from FreeIPA using ipa-getcert and calls a
 partner script to deploy the certificate to a VMware appliance via REST API.
 
-    FQDN          Fully qualified name of the VMware appliance web interface.
-                  Must be reachable from this host on port TCP/443.
-    -c CERT_CN    REQUIRED. Common Name (Subject) of the certificate (must be a
-                  FQDN). Will also present in the certificate as a SAN.
-    -a CRED_FILE  File with VMware credentials in plain text or base64 format.
-                  Defaults to /etc/ipa/.vmwrc
+    FQDN              Fully qualified name of the VMware appliance web interface.
+                      Must be reachable from this host on port TCP/443.
+    -c CERT_CN        REQUIRED. Common Name (Subject) of the certificate (must be a
+                      FQDN). Will also present in the certificate as a SAN.
+    -a CRED_FILE      File with VMware credentials in plain text or base64 format.
+                      Defaults to /etc/ipa/.vmwrc
 OPTIONS:
-    -G TYPE       Type of key to be generated if one is not already in place.
-                  IPA CA uses RSA by default. (RSA, DSA, EC or ECDSA)
-    -b BITS       In case a new key pair needs to be generated, this option
-                  specifies the size of the key. Default: 2048 (RSA/DSA).
-                  EC: 256, 384 or 512. See certmonger.conf for the default.
+    -i IP4            IPv4 address of the vCenter server, for inclusion in the SAN.
+    -S SERVICE        Service of the Service Principal. Default: HTTP.
+    -T CERT_PROFILE   Ask IPA to process the request using the named profile or
+                      template.
+    -G TYPE           Type of key to be generated if one is not already in place.
+                      IPA CA uses RSA by default. (RSA, DSA, EC or ECDSA)
+    -b BITS           In case a new key pair needs to be generated, this option
+                      specifies the size of the key. Default: 2048 (RSA/DSA).
+                      EC: 256, 384 or 512. See certmonger.conf for the default.
 
-    -h            Display this help and exit.
-    -v            Verbose mode.
+    -h                Display this help and exit.
+    -v                Verbose mode.
 EOF
 }
 
@@ -36,6 +40,12 @@ while getopts c:a:G:b:vh opt; do
         c)  CERT_CN=$OPTARG
             ;;
         a)  CRED_FILE=$OPTARG
+            ;;
+        i)  IP4=$OPTARG
+            ;;
+        S)  SERVICE=$OPTARG
+            ;;
+        T)  CERT_PROFILE=$OPTARG
             ;;
         G)  TYPE=$OPTARG
             ;; 
@@ -84,10 +94,31 @@ else
     exit 5
 fi
 
+# Check that the IPv4 address is valid if parsed
+if [[ ! -z $IP4 ]]; then
+    if expr "$OPTARG" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
+        IPS=.
+        set $OPTARG
+        for quad in 1 2 3 4; do
+            if eval [ \$$quad -gt 255 ]; then
+                printf 'ERROR: Invalid IPv4 address provided: %s\n' "$OPTARG"
+                exit 2
+            fi
+        done
+        IP4=$OPTARG
+        IP4_log="  IP4: $IP4\n"
+    else
+        printf 'ERROR: Invalid IPv4 address provided: %s\n' "$OPTARG"
+        exit 2
+    fi
+else
+    IP4_log=""
+fi
+
 # Check that a single valid FQDN was parsed for the VMware REST API interface
 if grep -q -P '(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}\.)+[a-zA-Z]{2,63}$)' <<< "$@"; then
     VMW_MGMT="${@,,}"
-    printf '  verbose=%d\n  CERT_CN: %s\n  VMW_FQDN: %s\n' "$VERBOSE" "$CERT_CN" "$VMW_MGMT"
+    printf '  verbose=%d\n  CERT_CN: %s\n%s  VMW_FQDN: %s\n' "$VERBOSE" "$CERT_CN" "$IP4_log" "$VMW_MGMT"
     if ! nc -z $VMW_MGMT 443 2>/dev/null; then
         printf 'ERROR: VMware device unreachable at: https://%s/\n' "$VMW_MGMT"
         exit 4
@@ -97,6 +128,21 @@ else
     printf 'Parsed string: %s\n\n' "$@"
     show_help >&2
     exit 4
+fi
+
+# Set the default service for the Service Principal
+if [[ -z $SERVICE ]]; then
+    SERVICE="HTTP"
+fi
+
+# Verify a valid IPA CA Certificate Profile is parsed
+if [[ ! -z $CERT_PROFILE ]]; then
+    if ! (ipa certprofile-find --id="$CERT_PROFILE"); then
+        printf "ERROR: Certificate profile %s doesn't exist\n" "$CERT_PROFILE"
+        exit 6
+    else
+        (( $VERBOSE > 0 )) && printf 'Found certificate profile: %s\n' "$CERT_PROFILE"
+    fi
 fi
 
 # Verify the parsed certificate type and bit length
@@ -122,12 +168,24 @@ if [[ ! -z $TYPE ]]; then
     fi
 fi
 
+## Options
+# Parse IPA CA Certificate Profile to ipa-getcert
+if [[ -z $CERT_PROFILE ]]; then
+    IPA_OPTS=""
+else
+    IPA_OPTS="-T $CERT_PROFILE"
+fi
 # Parse certificate key type and length to ipa-getcert
 if [[ ! -z $TYPE ]]; then
     IPA_OPTS="$IPA_OPTS -G $TYPE"
     if [[ ! -z $BITS ]]; then
          IPA_OPTS="$IPA_OPTS -g $BITS"
     fi
+fi
+# Parse IPv4 SAN option to ipa-getcert
+if [[ ! -z $IP4 ]]; then
+    IPA_OPTS="$IPA_OPTS -A $IP4"
+    (( $VERBOSE > 0 )) && echo "IPv4 will be included in the SAN."
 fi
 
 ## Requirements
@@ -171,4 +229,3 @@ if [[ "$CERT_STAT" != "monitoring" ]]; then
     exit 10
 fi
 echo "FINISHED: Check the Vmware appliance to see if the certificate is in use."
-
